// <auto-generated />
using System;
using FinancialTransactions.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialTransactions.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialTransactions.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("FinancialTransactions.Domain.Entities.TransactionStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1e0e4b0-9e56-4f1d-9f8c-1e65a27a3e10"),
                            Name = "Active"
                        },
                        new
                        {
                            Id = new Guid("93fbdabc-204c-4b61-9a12-2f21fb3d3a09"),
                            Name = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("5a2f9e5d-1ddf-4a7f-9c9a-f3dbdb2e08e0"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("1c0f5f5d-5949-4b66-9d1a-d4b2d86c8271"),
                            Name = "Completed"
                        },
                        new
                        {
                            Id = new Guid("0f5d30be-0ef1-4c5d-a1b8-90c76cc85bbf"),
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("FinancialTransactions.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("FinancialTransactions.Domain.Entities.TransactionStatus", "Status")
                        .WithMany("Transactions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FinancialTransactions.Domain.Entities.TransactionStatus", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
